http:
  routers:
    # HTTP Routers
    medicaocular-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^medicaocular\.ddev\.site$`)
      service: "medicaocular-phpmyadmin-80"
      ruleSyntax: v3
      tls: false

    medicaocular-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^medicaocular\.ddev\.site$`)
      service: "medicaocular-web-80"
      ruleSyntax: v3
      tls: false

    medicaocular-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^medicaocular\.ddev\.site$`)
      service: "medicaocular-web-8025"
      ruleSyntax: v3
      tls: false

    medicaocular-web-3000-http:
      entrypoints:
        - http-3001
      rule: HostRegexp(`^medicaocular\.ddev\.site$`)
      service: "medicaocular-web-3000"
      ruleSyntax: v3
      tls: false

    # HTTPS Routers
    medicaocular-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^medicaocular\.ddev\.site$`)
      service: "medicaocular-phpmyadmin-80"
      ruleSyntax: v3
      tls: true

    medicaocular-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^medicaocular\.ddev\.site$`)
      service: "medicaocular-web-80"
      ruleSyntax: v3
      tls: true

    medicaocular-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^medicaocular\.ddev\.site$`)
      service: "medicaocular-web-8025"
      ruleSyntax: v3
      tls: true

    medicaocular-web-3000-https:
      entrypoints:
        - http-3000
      rule: HostRegexp(`^medicaocular\.ddev\.site$`)
      service: "medicaocular-web-3000"
      ruleSyntax: v3
      tls: true

  middlewares:
    medicaocular-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    medicaocular-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-medicaocular-phpmyadmin:80

    medicaocular-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-medicaocular-web:80

    medicaocular-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-medicaocular-web:8025

    medicaocular-web-3000:
      loadbalancer:
        servers:
          - url: http://ddev-medicaocular-web:3000

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/medicaocular.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/medicaocular.key
