<?php return array(
    'root' => array(
        'pretty_version' => '3.0.19',
        'version' => '3.0.19.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'grocery-crud/deployment',
        'dev' => true,
    ),
    'versions' => array(
        'grocery-crud/deployment' => array(
            'pretty_version' => '3.0.19',
            'version' => '3.0.19.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'grocery-crud/enterprise' => array(
            'pretty_version' => '3.1.6',
            'version' => '3.1.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grocery-crud/enterprise',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'laminas/laminas-db' => array(
            'pretty_version' => '2.20.0',
            'version' => '2.20.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-db',
            'aliases' => array(),
            'reference' => '207b9ee70a8b518913c1fad688d7a64fe89a8b91',
            'dev_requirement' => false,
        ),
        'laminas/laminas-stdlib' => array(
            'pretty_version' => '3.19.0',
            'version' => '3.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-stdlib',
            'aliases' => array(),
            'reference' => '6a192dd0882b514e45506f533b833b623b78fff3',
            'dev_requirement' => false,
        ),
        'scoumbourdis/phpexcel' => array(
            'pretty_version' => '1.9.6',
            'version' => '1.9.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../scoumbourdis/phpexcel',
            'aliases' => array(),
            'reference' => '1abb20ad08829caeb971e2198d35e2c30e6a08cf',
            'dev_requirement' => false,
        ),
        'scoumbourdis/upload' => array(
            'pretty_version' => '1.3.3',
            'version' => '1.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../scoumbourdis/upload',
            'aliases' => array(),
            'reference' => '52a18218659468827156010b8451163d9455e2a8',
            'dev_requirement' => false,
        ),
        'vlucas/valitron' => array(
            'pretty_version' => 'v1.4.11',
            'version' => '1.4.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/valitron',
            'aliases' => array(),
            'reference' => 'fadce39f5f235755bb9794b2573af2d5bfcba85f',
            'dev_requirement' => false,
        ),
    ),
);
